### ISSUE TITLE
CDN redirect should redirect to aliases

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#926] opened 2022-01-25 08:41 UTC
When accessing a node via it's id on CDN redirect, the redirect should go to the alias if it exists, since only this path is rendered in the frontend.

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by chindris** [comment] 2022-02-06 05:53
Hi @pmelab !
I have issues reproducing this issue... I tried it locally within the silverback drupal as well as on a running project (nuklearforum) and accessing a node id via the cdn redirect returns a proper response.
Example: curl -I https://cms.nuklearforum.ch/cdn-redirect/de/node/59

Theoretically, I could see it happen if, during a cdn redirect request, both redirect request subscribers would have to kick in (basially, if a cdn redirect request would need two redirects to get to the proper path). In that case, the CDN Redirect controller would basically stop after the first redirect. A possible fix would be to keep doing a request while the event which generated the response has stopped propagating (because that is an indication that there are possibly other subscribers which did not run and which could generate another redirect).

But in this specific case (accessing a node via its id), the RedirectRequestSubscriber should already respond with the path alias...

**Comment by chindris** [comment] 2022-02-06 08:54
Hi @pmelab!

without the redirect module, the issue can be reproduced. I added a fix for this in https://github.com/AmazeeLabs/silverback-mono/pull/944

**Closed as completed** 2022-05-26 04:44 UTC
Labels: gatsby, drupal
